# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd568fc77a34ad9587cbcc2321e382b82300ed3122917d20622e8b6dfbe1f40a613150f3799a3f09638a64a2df34542ae3ccdd8e3680da86ff263ffc3edb68a9

test:
  secret_key_base: 0731cc884c3e53e0be5ce9f72f848bb59676190b90201b17c0d7a604157bdaf9e400a1d7de4a571c27dd6a925b505a4f022c40292278dffe63315cdfb330bb98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
